import { Footer } from '@/components/common/Layout/Footer/Footer'
import Header from '@/components/common/Layout/Header/Header'
import MovieLayout from '@/components/common/Layout/MovieLayout/MovieLayout'
import { MoviesProps } from '@/components/common/Layout/MovieLayout/_fragments/Movie.data'
import useCognitoUser from '@/components/hooks/useCognitoUser'
import { MY_IMAGE } from '@/generated/path/images'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect } from 'react'

function FuturePage({ datas }: MoviesProps) {
  const router = useRouter()
  useEffect(() => {
    const currentUser = useCognitoUser().getCurrentUser()
    if (!currentUser) router.push('/')
  }, [])

  return (
    <>
      <Head>
        <title>{'M.Z | 상영 예정작'}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={MY_IMAGE.LOGO} />
      </Head>
      <Header />
      <MovieLayout datas={datas} />
      <Footer />
    </>
  )
}

export default FuturePage
