import { MY_IMAGE } from "@/generated/path/images";
import Head from "next/head";
import { useRouter } from "next/router";
import React, { useState } from "react";
import styled from "styled-components";
import userPool from "@/components/hooks/usePool";

const Main = styled.div`
  height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
`;

const Container = styled.div`
  width: 600px;
  height: 600px;
  display: flex;
  justify-content: center;
  align-items: center;
  color: white;
`;

const LoginBox = styled.div`
  width: 80%;
  height: 60%;
  color: white;
  > * {
    font-weight: bold;
  }
`;

const LogoBox = styled.div`
  width: 100%;
  text-align: center;
`;

const Text = styled.div`
  text-align: center;
  font-size: 12px;
  font-weight: bold;
  color: white;
  margin-left: 10px;
`;

const Title = styled.div`
  font-size: 25px;
  text-align: center;
  font-weight: bold;
  margin-top: 20px;
  margin-bottom: 10px;
`;

const InputBox = styled.div`
  display: flex;
  width: 100%;
  align-items: center;
  margin-top: 20px;
`;

const InputTitle = styled.div`
  width: 30%;
  text-align: right;
  margin-right: 10px;
`;

const InputText = styled.input`
  width: 70%;
  height: 35px;
  backgronud-color: white;
  border-radius: 15px;
  border: none;
  padding-left: 10px;
  font-size: 12px;
`;

const ButtonDiv = styled.div`
  margin-top: 20px;
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: space-between;
  & > button {
    width: 45%;
    background-color: red;
    color: white;
    border: none;
    padding: 15px;
    cursor: pointer;
    font-weight: bolder;
    border-radius: 10px;
  }
`;

const Error = styled.div`
  margin-top: 10px;
  width: 100%;
  text-align: center;
  color: red;
  font-size: 13px;
`;

function SignUp() {
  const [memberData, setMemberData] = useState({
    email: "",
    pw: "",
    rePw: "",
  });
  const [idErrorState, setIdErrorState] = useState(false);
  const [pwErrorState, setPwErrorState] = useState(false);
  const [notSamePw, setNotSamePw] = useState(false);
  const [existed, setExisted] = useState(false);
  const router = useRouter();

  // const idRegex = /^[a-z]+[a-z0-9]{5,13}$/;
  // const pwRegex = /^(?=.*\d)(?=.*[a-zA-Z])[0-9a-zA-Z]{5,16}$/;

  const onSignUp = async () => {
    console.log(memberData);
    if (memberData.pw !== memberData.rePw) {
      setNotSamePw(true);
      return;
    }
    setNotSamePw(false);
    userPool.signUp(memberData.email, memberData.pw, [], [], (err, data) => {
      if (err) {
        console.log(err.message);
        if (err.message.includes("Password not long enough")) {
          setIdErrorState(false);
          setPwErrorState(true);
          setExisted(false);
          return;
        } else if (err.message.includes("Username should be an email.")) {
          setIdErrorState(true);
          setPwErrorState(false);
          setExisted(false);
          return;
        } else if (err.message.includes("email already exists")) {
          setIdErrorState(false);
          setPwErrorState(false);
          setExisted(true);
        }
        return;
      }
      setPwErrorState(false);
      setIdErrorState(false);
      setExisted(false);
      alert("회원가입 완료!");
      router.push("/verify");
    });
  };

  const inputData = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { value, name } = e.target;
    setMemberData((prev) => ({ ...prev, [name]: value }));
  };
  return (
    <>
      <Head>
        <title>{"M.Z | 회원가입"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={MY_IMAGE.LOGO} />
      </Head>
      <Main>
        <Container>
          <LoginBox>
            <LogoBox>
              <img src={MY_IMAGE.LOGO_FULL_NAME} />
            </LogoBox>
            <Title>{"회원가입"}</Title>
            <InputBox>
              <InputTitle>{"이메일: "}</InputTitle>
              <InputText
                onChange={(e) => inputData(e)}
                name="email"
                type={"text"}
                required
                placeholder="이메일을 입력해주세요"
              />
            </InputBox>
            <Text>{"*인증이 가능한 이메일로 입력해주세요"}</Text>

            <InputBox>
              <InputTitle>{"비밀번호: "}</InputTitle>
              <InputText
                name="pw"
                required
                type={"password"}
                placeholder="비밀번호(영어 소문자,숫자 혼합 8 ~ 17자)"
                onChange={(e) => inputData(e)}
                maxLength={17}
              />
            </InputBox>
            <InputBox>
              <InputTitle>{"비밀번호확인: "}</InputTitle>
              <InputText
                name="rePw"
                required
                type={"password"}
                placeholder="비밀번호를 한번 더 입력해주세요."
                onChange={(e) => inputData(e)}
                maxLength={17}
              />
            </InputBox>
            {idErrorState && <Error>{"이메일을 제대로 입력해주세요"}</Error>}
            {pwErrorState && <Error>{"비밀번호를 제대로 입력해주세요"}</Error>}
            {notSamePw && <Error>{"비밀번호가 일치하지 않습니다"}</Error>}
            {existed && <Error>{"이미 존재하는 계정입니다"}</Error>}
            <ButtonDiv>
              <button onClick={onSignUp}>{"회원가입"}</button>
              <button onClick={() => router.push("/")}>{"뒤로"}</button>
            </ButtonDiv>
          </LoginBox>
        </Container>
      </Main>
    </>
  );
}

export default SignUp;
