import { Footer } from "@/components/common/Layout/Footer/Footer";
import Header from "@/components/common/Layout/Header/Header";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";
import Main from "./_fragments/Main";

function BoardInfor() {
  const router = useRouter();
  const { id } = router.query;
  useEffect(() => {
    console.log(id);
  }, [id]);
  return (
    <>
      <Head>
        <title>{"M.Z | 게시판"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Main id={id} />
      {/* <MovieLayout movies={movies} /> */}
      <Footer />
    </>
  );
}

export default BoardInfor;
