import { Footer } from '@/components/common/Layout/Footer/Footer'
import Header from '@/components/common/Layout/Header/Header'
import { MY_IMAGE } from '@/generated/path/images'
import Head from 'next/head'
import styled from 'styled-components'
import { INFO_TITLE } from './_fragments/memberInfo.data'
import { getLocalStorage } from '@/utils/localstorage/localstorage'
import { useEffect, useState } from 'react'

const Container = styled.div`
  min-height: 800px;
  width: 60%;
  margin: auto;
  @media screen and (max-width: 1024px) {
    width: 100%;
  }
`

const MainTitle = styled.div`
  color: white;
  width: 100%;
  text-align: center;
  margin-top: 60px;
  font-weight: bold;
  font-size: 30px;
  position: relative;
`

const MainBox = styled.div`
  width: 100%;
  margin: 40px auto;
  background-color: white;
  border-radius: 10px;
  min-height: 500px;
  border: 1px solid white;
  text-align: center;
  @media screen and (max-width: 1024px) {
    border-radius: 0;
  }
`

const InforContainer = styled.div`
  width: 80%;
  margin: auto;
  height: 100%;
`

const InforBox = styled.div`
  display: flex;
  margin: 50px 0px;
  align-items: center;
`

const InforTitle = styled.div`
  width: 30%;
  text-align: right;
  font-weight: bolder;
`

const InforContent = styled.input`
  width: 70%;
  margin: 0px 10px;
  padding: 10px;
  border-radius: 10px;
  border: 1px solid gray;
`

const Button = styled.button`
  margin: 10px;
  padding: 5px 20px;
  background-color: red;
  border: none;
  color: white;
  border-radius: 10px;
  font-weight: bolder;
  cursor: pointer;
`

export default function InforPage() {
  const [email, setEmail] = useState<any>(null)
  const [updateData, setUpdateData] = useState({
    email: '',
    pw: '',
    rePw: '',
  })

  useEffect(() => {
    setEmail(getLocalStorage())
  }, [getLocalStorage()])

  const onUpdate = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { value, name } = e.target
    setUpdateData((prev) => ({ ...prev, [name]: value }))
  }

  const changeUserInfo = () => {
    const data = updateData
    if (!updateData.email) data.email = email
    console.log(updateData)
  }
  return (
    <>
      <Head>
        <title>{'M.Z | 회원정보'}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={MY_IMAGE.LOGO} />
      </Head>
      <Header />
      <Container>
        <MainTitle>{'회원정보'}</MainTitle>
        <MainBox>
          <InforContainer>
            {INFO_TITLE.map((item) => (
              <>
                <InforBox key={item.id}>
                  <InforTitle>{`${item.text}:`}</InforTitle>
                  <InforContent
                    defaultValue={item.name === 'email' ? email : ''}
                    type={item.name === 'email' ? 'text' : 'password'}
                    name={item.name}
                    onChange={(e) => onUpdate(e)}
                    placeholder={
                      item.name === 'pw'
                        ? '비밀번호(영어 소문자,숫자 혼합 8 ~ 17자)'
                        : ''
                    }
                  />
                </InforBox>
              </>
            ))}
          </InforContainer>
          <Button onClick={changeUserInfo}>{'변경'}</Button>
        </MainBox>
      </Container>
      <Footer />
    </>
  )
}
