import { Footer } from '@/components/common/Layout/Footer/Footer'
import Header from '@/components/common/Layout/Header/Header'
import { MY_IMAGE } from '@/generated/path/images'
import Head from 'next/head'
import styled from 'styled-components'

const Container = styled.div`
  min-height: 800px;
  width: 80%;
  margin: auto;
  @media screen and (max-width: 1024px) {
    width: 100%;
  }
`

const MainTitle = styled.div`
  color: white;
  width: 100%;
  text-align: center;
  margin-top: 60px;
  font-weight: bold;
  font-size: 30px;
  position: relative;
`

const MainBox = styled.div`
  width: 100%;
  margin: 40px auto;
  background-color: white;
  border-radius: 10px;
  min-height: 500px;
  border: 1px solid white;
  text-align: center;
  @media screen and (max-width: 1024px) {
    border-radius: 0;
  }
`

const InforContainer = styled.div`
  width: 80%;
  margin: auto;
  height: 100%;
`

const InforBox = styled.div`
  display: flex;
  margin: 50px 0px;
  align-items: center;
`

const InforTitle = styled.div`
  width: 30%;
  text-align: right;
  font-weight: bolder;
`

const InforContent = styled.div`
  width: 70%;
`

const Button = styled.button`
  margin: 10px;
  padding: 5px 20px;
  background-color: red;
  border: none;
  color: white;
  border-radius: 10px;
  font-weight: bolder;
  cursor: pointer;
`

export default function InforPage() {
  return (
    <>
      <Head>
        <title>{'M.Z | 회원정보'}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={MY_IMAGE.LOGO} />
      </Head>
      <Header />
      <Container>
        <MainTitle>{'회원정보'}</MainTitle>
        <MainBox>
          <InforContainer>
            <InforBox>
              <InforTitle>이메일:</InforTitle>
              <InforContent>test1234@naver.com</InforContent>
            </InforBox>
            <InforBox>
              <InforTitle>비밀번호:</InforTitle>
              <InforContent>content</InforContent>
            </InforBox>
            <InforBox>
              <InforTitle>비밀번호 확인:</InforTitle>
              <InforContent>content</InforContent>
            </InforBox>
            <InforBox>
              <InforTitle>title</InforTitle>
              <InforContent>content</InforContent>
            </InforBox>
          </InforContainer>
          <Button>{'변경'}</Button>
        </MainBox>
      </Container>
      <Footer />
    </>
  )
}
