import { Footer } from "@/components/common/Layout/Footer/Footer";
import Header from "@/components/common/Layout/Header/Header";
import { MY_IMAGE } from "@/generated/path/images";
import Head from "next/head";
import Main from "./_fragments/Main";

function BoardDetail({ detail }: any) {
  return (
    <>
      <Head>
        <title>{"M.Z | 게시판"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={MY_IMAGE.LOGO} />
      </Head>
      <Header />
      <Main detail={detail} />
      <Footer />
    </>
  );
}

export default BoardDetail;
