import { Footer } from "@/components/common/Layout/Footer/Footer";
import Header from "@/components/common/Layout/Header/Header";
import { MY_IMAGE } from "@/generated/path/images";
import Head from "next/head";
import styled from "styled-components";
import Content from "./_fragments/Content";
import Title from "./_fragments/Title";

import { CONFIG } from "../../../../config";
import { useState } from "react";

type Movie = {
  id: number;
  title: string;
  overview: string;
  poster_path: string;
};

type MoviesProps = {
  movies: Movie[];
};

const Main = styled.div`
  color: red;
  min-height: 600px;
`;

function MainPage({ movies }: MoviesProps) {
  // const callData = async () => {
  //   const result = await axios({
  //     method: "get",
  //     url: `${CONFIG.API_URL}/movie/popular?api_key=${CONFIG.API_KEY}&language=ko-KR&sort_by=popularity.desc&release_date.gte=2020-01-01&release_date.lte=2022-03-20&page=2`,
  //   });
  //   console.log(result);
  // };

  // useEffect(() => {
  //   callData();
  // }, []);
  console.log(movies);
  const [list, setList] = useState([]);

  return (
    <>
      <Head>
        <title>{"메인 페이지"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Main>
        <Title />
        <Content movies={movies} />
      </Main>
      <Footer />
    </>
  );
}

export default MainPage;
