import { MY_IMAGE } from "@/generated/path/images";
import Head from "next/head";
import { useRouter } from "next/router";
import React, { useState } from "react";
import styled from "styled-components";

const Main = styled.div`
  height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
`;

const Container = styled.form`
  width: 600px;
  height: 600px;
  display: flex;
  justify-content: center;
  align-items: center;
  color: white;
`;

const LoginBox = styled.div`
  width: 80%;
  height: 60%;
  color: white;
  > * {
    font-weight: bold;
  }
`;

const LogoBox = styled.div`
  width: 100%;
  text-align: center;
`;

const Title = styled.div`
  font-size: 25px;
  text-align: center;
  font-weight: bold;
  margin-top: 20px;
  margin-bottom: 10px;
`;

const InputBox = styled.div`
  display: flex;
  width: 100%;
  align-items: center;
  margin-top: 20px;
`;

const InputTitle = styled.div`
  width: 30%;
  text-align: right;
  margin-right: 10px;
`;

const InputText = styled.input`
  width: 70%;
  height: 35px;
  backgronud-color: white;
  border-radius: 15px;
  border: none;
  padding-left: 10px;
  font-size: 12px;
`;

const ButtonDiv = styled.div`
  margin-top: 20px;
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: space-between;
  & > button {
    width: 45%;
    background-color: red;
    color: white;
    border: none;
    padding: 15px;
    cursor: pointer;
    font-weight: bolder;
    border-radius: 10px;
  }
`;

function SignUp() {
  const [memberData, setMemberData] = useState({
    loginID: "",
    loginPW: "",
    sameLoginPW: "",
  });

  const router = useRouter();
  const goBack = (e: React.MouseEvent<HTMLButtonElement>) => {
    e.preventDefault();
    router.push("/");
  };

  const onSignUp = (e: React.MouseEvent<HTMLButtonElement>) => {
    e.preventDefault();
    console.log(memberData);
  };

  const inputSignData = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { value, name } = e.target;
    setMemberData((prev) => ({ ...prev, [name]: value }));
    console.log({ [name]: value });
  };
  return (
    <>
      <Head>
        <title>{"M.Z | 회원가입"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={MY_IMAGE.LOGO} />
      </Head>
      <Main>
        <Container>
          <LoginBox>
            <LogoBox>
              <img src={MY_IMAGE.LOGO_FULL_NAME} />
            </LogoBox>
            <Title>{"회원가입"}</Title>
            <InputBox>
              <InputTitle>{"아이디: "}</InputTitle>
              <InputText
                onChange={(e) => inputSignData(e)}
                name="loginID"
                required
                placeholder="아이디를 입력해주세요."
              />
            </InputBox>
            <InputBox>
              <InputTitle>{"비밀번호: "}</InputTitle>
              <InputText
                name="loginPW"
                required
                type={"password"}
                placeholder="비밀번호를 입력해주세요."
                onChange={(e) => inputSignData(e)}
              />
            </InputBox>
            <InputBox>
              <InputTitle>{"비밀번호확인: "}</InputTitle>
              <InputText
                name="sameLoginPW"
                required
                type={"password"}
                placeholder="비밀번호를 한번 더 입력해주세요."
                onChange={(e) => inputSignData(e)}
              />
            </InputBox>
            <ButtonDiv>
              <button onClick={(e) => onSignUp(e)}>{"회원가입"}</button>
              <button onClick={(e) => goBack(e)}>{"뒤로"}</button>
            </ButtonDiv>
          </LoginBox>
        </Container>
      </Main>
    </>
  );
}

export default SignUp;
