import { MY_IMAGE } from "@/generated/path/images";
import Head from "next/head";
import { useEffect, useState } from "react";
import styled from "styled-components";

const Main = styled.div`
  height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
`;

const LoginContainer = styled.form`
  width: 600px;
  height: 600px;
  display: flex;
  justify-content: center;
  align-items: center;
`;

const LoginBox = styled.div`
  width: 80%;
  height: 60%;
  color: white;
  > * {
    font-weight: bold;
  }
`;

const LogoBox = styled.div`
  width: 100%;
  text-align: center;
`;

const Title = styled.div`
  font-size: 25px;
  text-align: center;
  font-weight: bold;
  margin-top: 20px;
  margin-bottom: 10px;
`;

const InputBox = styled.div`
  display: flex;
  width: 100%;
  align-items: center;
  margin-top: 20px;
`;

const InputTitle = styled.div`
  width: 30%;
  text-align: right;
  margin-right: 10px;
`;

const InputText = styled.input`
  width: 70%;
  height: 35px;
  backgronud-color: white;
  border-radius: 15px;
  border: none;
  padding-left: 10px;
  font-size: 12px;
`;

const LoginButton = styled.button`
  margin-top: 20px;
  width: 100%;
  background-color: red;
  color: white;
  border: none;
  padding: 15px;
  cursor: pointer;
`;

export default function LoginPage() {
  return (
    <>
      <Head>
        <title>{"무비존"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <LoginContainer>
          <LoginBox>
            <LogoBox>
              <img src={MY_IMAGE.LOGO_FULL_NAME} />
            </LogoBox>
            <Title>{"로그인"}</Title>
            <InputBox>
              <InputTitle>{"아이디: "}</InputTitle>
              <InputText placeholder="아이디를 입력해주세요." />
            </InputBox>
            <InputBox>
              <InputTitle>{"비밀번호: "}</InputTitle>
              <InputText
                type={"password"}
                placeholder="비밀번호를 입력해주세요."
              />
            </InputBox>
            <LoginButton>{"LOGIN"}</LoginButton>
          </LoginBox>
        </LoginContainer>
      </Main>
    </>
  );
}
