import { Footer } from "@/components/common/Layout/Footer/Footer";
import Header from "@/components/common/Layout/Header/Header";
import Head from "next/head";
import styled from "styled-components";
import BoardContent from "./_fragments/BoardContent";

function BoardPage() {
  return (
    <>
      <Head>
        <title>{"M.Z | 게시판"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <BoardContent />
      {/* <MovieLayout movies={movies} /> */}
      <Footer />
    </>
  );
}

export default BoardPage;
