import { Footer } from '@/components/common/Layout/Footer/Footer'
import Header from '@/components/common/Layout/Header/Header'
import { MY_IMAGE } from '@/generated/path/images'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'
import Main from './_fragments/Main'
import useCognitoUser from '@/components/hooks/useCognitoUser'

function BoardPage({ lists }: any) {
  const router = useRouter()
  console.log(lists.length)
  useEffect(() => {
    const currentUser = useCognitoUser().getCurrentUser()

    if (!currentUser) router.push('/')
  }, [])

  return (
    <>
      <Head>
        <title>{'M.Z | 게시판'}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={MY_IMAGE.LOGO} />
      </Head>
      <Header />
      <Main lists={lists} />
      <Footer />
    </>
  )
}

export default BoardPage
