import { Footer } from "@/components/common/Layout/Footer/Footer";
import Header from "@/components/common/Layout/Header/Header";
import Head from "next/head";
import styled from "styled-components";

const Container = styled.div`
  min-height: 600px;
  width: 100%;
`;

const Title = styled.div`
  color: white;
  width: 100%;
  text-align: center;
  margin-top: 60px;
  font-weight: bold;
  font-size: 30px;
  position: relative;
`;

const Content = styled.div`
  width: 80%;
  margin: auto;
  margin-top: 20px;
  min-height: 500px;
  border: 1px solid white;
`;

function BoardPage() {
  return (
    <>
      <Head>
        <title>{"M.Z | 게시판"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Container>
        <Title>{"게시판"}</Title>
        <Content></Content>
      </Container>
      {/* <MovieLayout movies={movies} /> */}
      <Footer />
    </>
  );
}

export default BoardPage;
