import Head from "next/head";
import { useEffect, useState } from "react";
import styled from "styled-components";

const Loading = styled.div`
  width: 100%;
  height: 100%;
  background-color: black;
  display: flex;
  align-items: center;
  justify-contents: center;
  color: red;
  margin: auto;
`;

export default function LoginPage() {
  const [mounting, setMounting] = useState(true);

  useEffect(() => {
    setTimeout(() => {
      setMounting(false);
    }, 3000);
  }, []);
  return (
    <>
      <Head>
        <title>{"무비존"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {mounting ? (
        <>
          {/* <Loading>Loading Test</Loading> */}
          <div>123</div>
        </>
      ) : (
        <div>loading 완료</div>
      )}
    </>
  );
}
