import { Footer } from "@/components/common/Layout/Footer/Footer";
import Header from "@/components/common/Layout/Header/Header";
import MovieLayout from "@/components/common/Layout/MovieLayout/MovieLayout";
import { MoviesProps } from "@/components/common/Layout/MovieLayout/_fragments/Movie.data";
import Head from "next/head";

function PastPage({ movies }: MoviesProps) {
  return (
    <>
      <Head>
        <title>{"M.Z | 지난 상영작"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <MovieLayout movies={movies} />
      <Footer />
    </>
  );
}

export default PastPage;
